# Generated by Django 6.0.6 on 2026-07-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactus_delete_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contact/'),
        ),
    ]
