"""
Django settings for HomeTex project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


MEDIA_ROOT = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--*fcm*my0(*(dfwff3jumjm$o*4tn*f2f@dn965157%)8s^&yk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.products',
    'apps.home',
    'apps.contact',
    'apps.social',
    'apps.aboutus', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'HomeTex.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates" ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.aboutus.context_processors.company_profile',
                'apps.social.context_processors.social_profiles'
            ],
        },
    },
]

WSGI_APPLICATION = 'HomeTex.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "hometex_db",
        "USER": "root",
        "PASSWORD": "mysql1234",
        "HOST": "localhost",
        "PORT": "3306",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",   
]


UNFOLD = {
    "SITE_TITLE": "Home Tex Admin",
    "SITE_HEADER": "Home Tex",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "COLORS": {
        "primary": {
            "50": "255 247 237",
            "500": "249 115 22",   
            "600": "234 88 12",
            "900": "124 45 18",
        },
    },
   "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,  
        "navigation": [
            {
                "title": "Dashboard",
                "separator": True,
                "items": [
                    {"title": "Home", "icon": "dashboard", "link": "/admin/"},
                ],
            },
            {
                "title": "Catalog",
                "separator": True,
                "items": [
                    {"title": "Products", "icon": "inventory_2", "link": "/admin/products/product/"},
                    {"title": "Categories", "icon": "category", "link": "/admin/products/category/"},
                    {"title": "Collections", "icon": "collections_bookmark", "link": "/admin/products/collection/"},
                ],
            },
            {
                "title": "Content",
                "separator": True,
                "items": [
                    {"title": "About Us", "icon": "info", "link": "/admin/aboutus/companyprofile/"},
                    {"title": "Vision & Mission", "icon": "flag", "link": "/admin/aboutus/visionmission/"},
                    {"title": "Blog Posts", "icon": "article", "link": "/admin/home/blogpost/"},
                ],
            },
            {
                "title": "Inquiries",
                "separator": True,
                "items": [
                    {"title": "Enquiries", "icon": "mail", "link": "/admin/contact/enquiry/"},
                ],
            },
            {
                "title": "Access",
                "separator": True,
                "collapsible": True,
                "items": [
                    {"title": "Users", "icon": "person", "link": "/admin/auth/user/"},
                    {"title": "Groups", "icon": "group", "link": "/admin/auth/group/"},
                ],
            },
        ],
    },
}