# Generated by Django 6.0.6 on 2026-07-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialprofile',
            name='handle',
        ),
        migrations.AlterField(
            model_name='socialprofile',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='social_logo'),
        ),
    ]
