# Generated by Django 6.0.6 on 2026-07-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=100, null=True)),
                ('about_text', models.TextField(blank=True, null=True)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='aboutus')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Company Profile',
            },
        ),
        migrations.CreateModel(
            name='VisionMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_title', models.CharField(default='Our Vision', max_length=200)),
                ('vision_text', models.TextField(blank=True, null=True)),
                ('mission_title', models.CharField(default='Our Mission', max_length=100)),
                ('mission_text', models.TextField(blank=True, null=True)),
                ('vision_image', models.ImageField(blank=True, null=True, upload_to='aboutus/')),
                ('mission_image', models.ImageField(blank=True, null=True, upload_to='aboutus/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vision & Mission',
            },
        ),
    ]
