# Generated by Django 6.0.6 on 2026-07-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, choices=[('star', 'Star (OEM/ODM)'), ('globe', 'Globe (Markets)'), ('shield', 'Shield (Quality)')], default='star', max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Why Choose Us Card',
                'verbose_name_plural': 'Why Choose Us Cards',
                'ordering': ['order', 'id'],
            },
        ),
    ]
