# Generated by Django 6.0.6 on 2026-07-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_whychooseus'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='aboutus'),
        ),
    ]
